import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {compute,referenceCheck,new2026,rankRows,validateDataset,rulesStatus,parseCSV,csvText,legacyIndividual} from '../src/core.mjs';
const demo=JSON.parse(await readFile(new URL('../src/demo-2025.json',import.meta.url),'utf8'));
const copy=x=>structuredClone(x);
function sample(){const d=new2026();d.participants=[{id:'P001',name:'A',dealer:'MD',groupId:'G01'},{id:'P002',name:'B',dealer:'MD',groupId:'G01'}];d.groups=[{id:'G01',name:'G'}];d.components=[{id:'test',label:'Test',scope:'individual',max:50,weight:70,enabled:true},{id:'obs',label:'Obs',scope:'individual',max:4,weight:30,enabled:true},{id:'task',label:'Task',scope:'group',max:4,weight:100,enabled:true}];d.individualScores=[{entityId:'P001',componentId:'test',value:40},{entityId:'P001',componentId:'obs',value:4},{entityId:'P002',componentId:'test',value:40},{entityId:'P002',componentId:'obs',value:null}];d.groupScores=[{entityId:'G01',componentId:'task',value:3}];return d;}
test('2025 contains 30 participants and 5 groups',()=>{assert.equal(demo.participants.length,30);assert.equal(demo.groups.length,5);});
test('all 35 recomputed totals match synthetic fixture',()=>{const v=referenceCheck(demo);assert.equal(v.matching,35);assert.equal(v.differences.length,0);});
test('every individual day reproduces fixture reference',()=>{for(const p of compute(demo,'individual'))p.days.forEach((v,i)=>assert.ok(Math.abs(v-p.reference.days[i])<1e-6,p.id+' day '+i));});
test('every group day reproduces fixture reference',()=>{for(const p of compute(demo,'group'))p.days.forEach((v,i)=>assert.ok(Math.abs(v-p.reference.days[i])<1e-6,p.id+' day '+i));});
test('individual champion and total',()=>{const x=compute(demo,'individual')[0];assert.equal(x.id,'P009');assert.equal(x.total,293.50000000000006);});
test('group champion and total',()=>{const x=compute(demo,'group')[0];assert.equal(x.id,'G05');assert.equal(x.total,711.01);});
test('rank ties use competition rank 1,1,3',()=>{assert.deepEqual(rankRows([{name:'A',total:10},{name:'B',total:10},{name:'C',total:9}]).map(r=>r.rank),[1,1,3]);});
test('null excluded, zero valid',()=>{const r=rankRows([{name:'A',total:null},{name:'B',total:0}]);assert.equal(r[0].rank,1);assert.equal(r[1].rank,null);});
test('2026 starts empty, no copied participant or score',()=>{const d=new2026();assert.equal(d.participants.length,0);assert.equal(d.individualScores.length,0);assert.equal(d.rulesApproved,false);assert.equal(rulesStatus(d,'individual').valid,false);});
test('2026 normalizes maximum and applies weights once',()=>{const r=compute(sample(),'individual');assert.equal(r[0].total,86);});
test('2026 blank is incomplete not zero',()=>{const r=compute(sample(),'individual');assert.equal(r.find(r=>r.id==='P002').total,null);assert.equal(r.find(r=>r.id==='P002').rank,null);});
test('2026 explicit zero remains rankable',()=>{const d=sample();d.individualScores.find(s=>s.entityId==='P002'&&s.componentId==='obs').value=0;assert.equal(compute(d,'individual').find(r=>r.id==='P002').total,56);});
test('2026 group score not added to individual',()=>{const d=sample();assert.equal(compute(d,'group')[0].total,75);d.groupScores[0].value=4;assert.equal(compute(d,'individual')[0].total,86);});
test('invalid weight sum blocks ranking',()=>{const d=sample();d.components[0].weight=80;assert.equal(compute(d,'individual')[0].total,null);});
test('duplicate participant rejected',()=>{const d=sample();d.participants.push(copy(d.participants[0]));assert.throws(()=>validateDataset(d),/duplikat/);});
test('unknown participant ID rejected',()=>{const d=sample();d.individualScores[0].entityId='P999';assert.throws(()=>validateDataset(d),/belum cocok/);});
test('duplicate score rejected',()=>{const d=sample();d.individualScores.push(copy(d.individualScores[0]));assert.throws(()=>validateDataset(d),/duplikat/);});
test('out of range rejected',()=>{const d=sample();d.individualScores[0].value=51;assert.throws(()=>validateDataset(d),/rentang/);});
test('negative value rejected',()=>{const d=sample();d.individualScores[0].value=-1;assert.throws(()=>validateDataset(d),/rentang/);});
test('missing legacy mandatory input remains incomplete',()=>{const p=copy(demo.participants[0]);p.legacyInputs.obs2=null;assert.equal(legacyIndividual(p).total,null);});
test('CSV handles multiline and escaped quotes',()=>{assert.deepEqual(parseCSV('a,b\r\n"x,y","z""w\nq"'),[['a','b'],['x,y','z"w\nq']]);});
test('CSV prevents formula injection',()=>{assert.match(csvText([['=1+1']]),/"'=1\+1"/);});
test('original data not mutated during calculation',()=>{const before=JSON.stringify(demo);compute(demo,'individual');compute(demo,'group');assert.equal(JSON.stringify(demo),before);});
